language: node_js
node_js:
  - "6.2.0"
env:
  - NODE_ENV=travis
install:
  - npm install
  - gulp gulp-release
branches:
  only:
    - master
cache:
  apt : true
  directories:
    - node_modules
deploy:
  provider: heroku
  app: my-file-upload
  skip_cleanup: true
  api_key:
    secure: "$HEROKU_APP_KEY"
notifications:
  email:
      - kulkarni.mak172@gmail.com
